### PR TITLE
first test for three r0.125.1

### PR DESCRIPTION
**Pull request by arpu**

### CODE REVIEW

**Comment by arpu** [comment]
@donmccurdy  do you think this can be complete ported to BufferGeometry?

**Comment by donmccurdy** [comment]
Eventually that is the goal — there's no reason this library couldn't use BufferGeometry entirely. I'm not sure how much work that would take though. Did you find any issues in the test here?

**Comment by arpu** [comment]
ok! no problems so far, i use this in my vrland build

**Comment by donmccurdy** [comment]
Handling this in https://github.com/donmccurdy/three-to-cannon/pull/38 — not quite ready to test the changes yet, a bit more to do, but would appreciate your help testing this out later on if you're able to! :)

**Pull request closed without merging**
