### PR TITLE
Fixed cylinder orientation.

### PR DESCRIPTION
**Pull request by MignonBelongie**
See https://github.com/n5ro/aframe-physics-system/issues/160
Unfortunately, I can't currently test this with the latest version of three-to-cannon, because aframe-physics-system can't (yet) use it. However, I do have a demo (https://glitch.com/~pleasant-feline-lyric) using aframe-physics-system that shows the bug and the fix. Change index.html to use bundle-with-bug-fixed.js instead of bundle-with-bug.js to see the effect of the bug fix. (Note: I added a couple of line endings in the two bundle files to isolate the change.)

### CODE REVIEW

**Comment by donmccurdy** [comment]
Thanks! You should be able to (locally) test this change with aframe-physics-system as follows:

```js
// in three-to-cannon/ folder:
npm link

// in aframe-physics-system-folder:
npm link three-to-cannon
npm run dist
```

That will rebuild aframe-physics-system using the local version of three-to-cannon, rather than the npm version. Does it give the right results for you then?

(After you're done, running `npm install` again on the aframe-physics-system folder will reset it to the normal state)

**Comment by MignonBelongie** [comment]
I had tried something like that, but it didn't work. I tried again using 'npm link' (which I did not know about - thanks) and the error is below. I think the problem is that index.js explicitly imports three/examples/jsm/math/ConvexHull.js


```
$ npm run dist

> aframe-physics-system@4.0.1 dist D:\src\n5ro\aframe-physics-system
> browserify index.js -o dist/aframe-physics-system.js && uglifyjs -c -o dist/aframe-physics-system.min.js -- dist/aframe-physics-system.js


D:\src\n5ro\forks\three-to-cannon\node_modules\three\examples\jsm\math\ConvexHull.js:8
import {
^.
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aframe-physics-system@4.0.1 dist: `browserify index.js -o dist/aframe-physics-system.js && uglifyjs -c -o dist/aframe-physics-system.min.js -- dist/aframe-physics-system.js`
npm ERR! Exit status 1

```

**Comment by donmccurdy** [comment]
Hm I see... that looks like the same problem you're likely to hit when trying to upgrade aframe-physics-system to the latest version of three-to-cannon... I may need to just bundle that file into this package, then. I'm not sure it will work with aframe-physics-system otherwise. I can do that.

In the meantime, could check the unit test (`npm test`) for this and make sure it looks right? It's possible that the orientation in the test is just wrong, and it would be great if we could fix the test to make sure it catches this in the future.

https://github.com/donmccurdy/three-to-cannon/blob/ea67eda0821b0ae91714aa3eb8453bd1d3f9c1f8/test/index.js#L46-L59

**Comment by MignonBelongie** [comment]
That test doesn't call createCylinderShape(), so I added a new test. The expected value for orientation.x (based on what's needed to work correctly with cannon.html) is the opposite of that for the already existing test ('shape - cylinder'). I considered whether createBoundingCylinderShape() should also be changed, and found that I could test that code with cannon.html by setting body="shape: cylinder". I discovered that in that case, an x rotation of either + or -90 works because the top and bottom radii are the same. Maybe it should be changed for consistency - I don't understand the code well enough to say.

**Comment by donmccurdy** [comment]
This looks great, thank you!

> Maybe it should be changed for consistency - I don't understand the code well enough to say.

Entirely possible — I think I'd just confirmed that it was working in my app at the time, and then used the rotation it gave.

**Pull request merged**
